### PR TITLE
Improvements to client setup

### PR DESCRIPTION
**Pull request by bengourley**
@Fauntleroy I've made some improvements to the way the client js is set up. Let me know if this suits your needs and addresses your concerns from #6?

You can `require('hot-rld/_client')` directly if you want the source JS but the main use case should be to load `require('hot-rld/client')` which loads the JS string that is required to populate a `<script>` tag.

### CODE REVIEW

**Comment by takempf** [comment]
If you use the function API you mentioned in https://github.com/bengourley/hot-rld/issues/6, you could do something like this in your server side code:

```js
<script>(${require('hot-rld/client').toString()})({ port: 12345 })</script>
```

While I could do this in mine:

```js
if (process.env.NODE_ENV === 'development') {
  const startClient = require('hot-rld/client');
  startClient({ port: 12345 });
}
```

This eliminates an extra file from the repo while leaving room for future configuration options to be passed to the client.

**Comment by takempf** [comment]
`require('hot-rld/_client')` will of course work, this is just a bonus suggestion.

**Comment by takempf** [comment]
(I'm going to keep all my replies from my pull req and https://github.com/bengourley/hot-rld/issues/6 here for simplicity's sake)

I'm using [`envify`](https://github.com/hughsk/envify) and [`uglify`](https://github.com/mishoo/UglifyJS2) to eliminate the code path where I include `hot-rld/client`. My code initially looks like this:

```js
// All my other application startup code here...

if (process.env.NODE_ENV === 'development') {
  const startClient = require('hot-rld/client');
  startClient({ port: 12345 });
}
```

After [`browserify`](http://browserify.org/) runs [`envify`](https://github.com/hughsk/envify) on my bundle (on my production server), it looks like this:

```js
// All my other application startup code here...

if ('production' === 'development') {
  var startClient = // reference hot-rld/client code here
  startClient({ port: 12345 });
}
```

I then run [`uglify`](https://github.com/mishoo/UglifyJS2), which eliminates unused code paths as part of optimization:

```js
// All my other application startup code here...
```

When I build my client side bundle locally, `process.env.NODE_ENV` resolves to "development" and the code remains. When I build my client side bundle in production/staging, `process.env.NODE_ENV` resolves to something different, so the code path is eliminated during minification.

**Comment by bengourley** [comment]
Cool so are you loading javascript with `hot-rld` or just css?

Because I would imagine that if you reloaded your bundle that includes the `hot-rld` client script it will reload the script once on the first change, twice on the second change, 3x… 4x etc…

**Comment by takempf** [comment]
Ah, good point. I'm just loading CSS so that's not a concern for me. If I
were to reload JS I'd probably just split my bundle to prevent that
scenario.

On Dec 2, 2016 9:15 AM, "Ben Gourley" <notifications@github.com> wrote:

Cool so are you loading javascript with hot-rld or just css?

Because I would imagine that if you reloaded your bundle that includes the
hot-rld client script it will reload the script once on the first change,
twice on the second change, 3x… 4x etc…

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bengourley/hot-rld/pull/8#issuecomment-264508319>, or mute
the thread

**Comment by bengourley** [comment]
Ahhh! Yeah this is why I sort of want to discourage the client being `require()`d into a bundle, and I guess why you probably thought _what the hell is he on about_ 😄 

I think for the way you want to use it `_client` feels a bit grimey so I think I'll put something together like you mentioned. I was thinking something like `stringify()` so glad to hear you mentioned `.toString()`, we're thinking along the same lines.

**Comment by bengourley** [comment]
Hey @Fauntleroy I found a neat solution to this that had dropped off my radar. Setting the `"browser"` key in package.json means that we can include a different source file dependent on whether you are in node or browserify.

If you could checkout this branch and use your workflow of `require('hot-rld/client')` and check this works nicely for you, let me know and I'll merge and publish.

**Pull request merged**
